// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package com.alibaba.android.dingtalk.redpackets.activities;
//
//import android.content.Intent;
//import android.os.Bundle;
//import android.os.Handler;
//import android.text.TextUtils;
//import android.view.MotionEvent;
//import android.view.View;
//import android.view.accessibility.AccessibilityNodeProvider;
//import android.view.animation.AccelerateInterpolator;
//import android.widget.Button;
//import android.widget.ImageButton;
//import android.widget.TextView;
//
//import com.aliaba.android.dingtalk.redpackets.base.RedPacketInterface;
//import com.aliaba.android.dingtalk.redpackets.base.views.RewardAvatarView;
//import com.alibaba.android.dingtalk.redpackets.RedPacketsBaseActivity;
//import com.alibaba.android.dingtalk.redpackets.models.RedPacketsClusterObject;
//import com.alibaba.android.dingtalk.redpackets.models.RedPacketsClusterPickingStatus;
//import com.alibaba.android.dingtalk.userbase.ContactInterface;
//import com.alibaba.android.dingtalk.userbase.model.OrgEmployeeExtensionObject;
//import com.alibaba.android.dingtalk.userbase.model.UserProfileObject;
//import com.alibaba.android.dingtalkbase.widgets.AvatarImageView;
//import com.alibaba.wukong.im.Conversation;
//import com.laiwang.framework.eventbus.EventButler;
//
//import java.util.ArrayList;
//import java.util.Arrays;
//import java.util.Comparator;
//import java.util.HashMap;
//
//public class PickRedPacketsActivity extends RedPacketsBaseActivity {
//    private RedPacketsClusterPickingStatus a;
//    private Conversation b;
//    private RedPacketsClusterObject c;`
//    private Button d;
//    private AvatarImageView e;
//    private View f;
//    private Handler g;
//    private ImageButton h;
//    private RewardAvatarView i;
//    private TextView j;
//    private TextView k;
//    private TextView l;
//    private TextView m;
//    private TextView n;
//
//    public PickRedPacketsActivity() {
//        g = new Handler();
//    }
//
//    protected void onCreate(Bundle savedInstanceState) {
//        super.onCreate(savedInstanceState);
//        setContentView(qj.d.activity_pick_redpackets);
//        View contentView = findViewById(qj.c.fr_content);
//        contentView.setMinimumHeight((int) ((double) un.b(this) * 0.67));
//        a = (RedPacketsClusterPickingStatus) getIntent().getSerializableExtra("pick_status");
//        b = (Conversation) getIntent().getSerializableExtra("conversation");
//        if (a.redEnvelopCluster != null) {
//            c = a.redEnvelopCluster;
//        } else if (a.detail != null) {
//            c = a.detail.redEnvelopCluster;
//        }
//        a();
//    }
//
//    private void a() {
//        n = (TextView) findViewById(qj.c.redpackets_random_detail);
//        n.setVisibility(0x8);
//        i = (RewardAvatarView) findViewById(qj.c.reward_view);
//        ArrayList<RewardAvatarView.a> rewardObjects = new ArrayList<RewardAvatarView.a>();
//        if (c.type == 0x2) {
//            Arrays.sort(c.receivers, new Comparator(this) {
//
//                1(
//                PickRedPacketsActivity p1
//                )
//
//                {
//                }
//
//                public int a(Long lhs, Long rhs) {
//                    long weightLeft = lhs.longValue();
//                    if (lhs.longValue() == rb.a().c()) {
//                        weightLeft = 0x0;
//                    }
//                    long weightRight = rhs.longValue();
//                    if (rhs.longValue() == rb.a().c()) {
//                        weightRight = 0x0;
//                    }
//                    -0x1;
//                    return -0x1;
//                }
//            });
//            i.setVisibility(0x0);
//            for (int i = 0x0; i < c.receivers.length; i = i + 0x1) {
//                RewardAvatarView.a rewardObject = new RewardAvatarView.a();
//                long uid = c.receivers[i].longValue();
//                UserProfileObject userProfileObject = ContactInterface.a().f(uid);
//                if (userProfileObject != null) {
//                    rewardObject.c = userProfileObject.avatarMediaId;
//                    rewardObject.d = userProfileObject.nick;
//                } else {
//                    rewardObject.d = String.valueOf(uid);
//                }
//                rewardObject.b = qj.b.redpackets_reward_default_avatar;
//                rewardObject.e = String.format("\u5171%d\u4eba", c.size);
//                rewardObjects.add(rewardObject);
//            }
//            i.setData(rewardObjects);
//        } else {
//            i.setVisibility(0x8);
//        }
//        f = findViewById(qj.c.ll_pick);
//        d = (Button) findViewById(qj.c.redpackets_detail);
//        e = (AvatarImageView) findViewById(qj.c.redpackets_enterprise_icon);
//        h = (ImageButton) findViewById(qj.c.btn_pick);
//        m = (TextView) findViewById(qj.c.redpackets_result);
//        m.setVisibility(0x8);
//        String orgName = qk.a(c.oid);
//        j = (TextView) findViewById(qj.c.sender_name);
//        j.setText(orgName);
//        k = (TextView) findViewById(qj.c.redpackets_desc);
//        k.setText(RedPacketInterface.a().a(c.congratulations, a.redEnvelopCluster.type));
//        l = (TextView) findViewById(qj.c.redpackets_money);
//        if (c.type == 0x2) {
//            l.setVisibility(0x0);
//            double sum = Double.parseDouble(c.amount);
//            if (c.size > 0x1) {
//                l.setText(String.format("%.2f", 0x1) + getString(qj.e.redpackets_yuan_per_one));
//            } else {
//                l.setText(String.format("%.2f", 0x1) + getString(qj.e.redpackets_yuan));
//            }
//            e.setVisibility(0x0);
//            ContactInterface contactInterface = (ContactInterface) tr.a().a(ContactInterface.class);
//            OrgEmployeeExtensionObject org = contactInterface.g(c.oid);
//            if ((org != null) && (org.orgDetail != null) && (!TextUtils.isEmpty(org.orgDetail.logoMediaId))) {
//                e.a(orgName, org.orgDetail.logoMediaId);
//            } else {
//                e.setImageResource(qj.b.redpackets_enterprise_default_logo);
//            }else{
//                l.setVisibility(0x8);
//                e.setVisibility(0x0);
//                e.a(String.valueOf(c.sender), 0x0);
//                ContactInterface.a().a(c.sender, (uf) EventButler.newCallback(new uf(this) {
//
//                    2(
//                    PickRedPacketsActivity p1
//                    )
//
//                    {
//                    }
//
//                    public void a(UserProfileObject userProfileObject) {
//                        a(a).a(userProfileObject.nick, userProfileObject.avatarMediaId);
//                        b(a).setText(userProfileObject.nick);
//                    }
//
//                    public void onException(String s, String s1) {
//                    }
//                }, uf.class, this));
//            }
//        }
//        TextView tvSize = (TextView) findViewById(qj.c.send_tips);
//        if (c.type == 0x2) {
//            tvSize.setVisibility(0x8);
//            d.setText(qj.e.redpackets_enterprise_show_detail);
//        } else if (c.type == 0x1) {
//            tvSize.setText(getString(qj.e.redpackets_tips_normal));
//            tvSize.setVisibility(0x0);
//            d.setText(qj.e.redpackets_show_detail);
//        } else {
//            tvSize.setText(getString(qj.e.redpackets_tips_random));
//            tvSize.setVisibility(0x0);
//            d.setText(qj.e.redpackets_show_detail);
//        }
//        if (a.pickStatus == 0) {
//            d.setVisibility(0x8);
//            f.setVisibility(0x0);
//            if (c.type == 0) {
//                n.setVisibility(0x0);
//            }
//        } else if (a.pickStatus == 0x2) {
//            d.setVisibility(0x0);
//            f.setVisibility(0x8);
//            m.setText(qj.e.redpackets_cant_pick_done);
//            k.setVisibility(0x8);
//            m.setVisibility(0x0);
//            l.setVisibility(0x8);
//        } else if (a.pickStatus == 0x3) {
//            d.setVisibility(0x0);
//            f.setVisibility(0x8);
//            m.setText(qj.e.redpackets_cant_pick_expired);
//            k.setVisibility(0x8);
//            m.setVisibility(0x0);
//            l.setVisibility(0x8);
//        } else {
//            d.setVisibility(0x0);
//            f.setVisibility(0x8);
//        }
//        h.setOnTouchListener(new View.OnTouchListener(this) {
//
//            3(
//            PickRedPacketsActivity p1
//            )
//
//            {
//            }
//
//            public boolean onTouch(View v, MotionEvent event) {
//                if ((event.getDeviceId() == 0) || (event.getDeviceId() == -0x1)) {
//                    return true;
//                }
//                return false;
//            }
//        });
//        if (un.b(0x10)) {
//            h.setAccessibilityDelegate(new View.AccessibilityDelegate(this) {
//                AccessibilityNodeProvider a;
//
//                4(
//                PickRedPacketsActivity p1
//                )
//
//                {
//                    a = new AccessibilityNodeProvider(this) {
//
//                        1(PickRedPacketsActivity.4p1)
//
//                        {
//                        }
//                    };
//                }
//
//                public AccessibilityNodeProvider getAccessibilityNodeProvider(View host) {
//                    return a;
//                }
//            });
//        }
//        h.setOnClickListener(new View.OnClickListener(this) {
//
//            5(
//            PickRedPacketsActivity p1
//            )
//
//            {
//            }
//
//            public void onClick(View v) {
//                if (c(a).type == 0x2) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_org_redenvelope_open", new String[0x0]);
//                } else if (d(a).type() == 0x1) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_normal_redenvelope_open", new String[0x0]);
//                } else {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_rand_redenvelope_open", new String[0x0]);
//                }
//                e(a).setEnabled(false);
//                a(a, e(a), 0.0f, 360.0f);
//                ra.a().b(Long.valueOf(c(a).sender), c(a).clusterId, new uf(this) {
//
//                    1(PickRedPacketsActivity.5p1)
//
//                    {
//                    }
//
//                    public void a(RedPacketsClusterPickingStatus redPacketsClusterPickingStatus) {
//                        h(a.a).postDelayed(new Runnable(this, redPacketsClusterPickingStatus) {
//
//                            1(PickRedPacketsActivity.5.1p1,
//                            RedPacketsClusterPickingStatus p2
//                            )
//
//                            {
//                            }
//
//                            public void run() {
//                                if (!b.a.a.isDestroyed()) {
//                                    e(b.a.a).clearAnimation();
//                                    e(b.a.a).setEnabled(true);
//                                    a(b.a.a, a);
//                                    vo.a("redpackets", "pick", "senderId:" + c(b.a.a).sender + " clusterId " + c(b.a.a).sender + " status " + f(b.a.a).pickStatus);
//                                    if (f(b.a.a).redEnvelopCluster != null) {
//                                        a(b.a.a, f(b.a.a).redEnvelopCluster);
//                                    } else if (f(b.a.a).detail != null) {
//                                        a(b.a.a, f(b.a.a).detail.redEnvelopCluster);
//                                    }
//                                    if (f(b.a.a).pickStatus == 0x1) {
//                                        Navigator.from(b.a.a).to("https://qr.dingtalk.com/page/red_packets/detail.html", new IntentRewriter(this) {
//
//                                            1(PickRedPacketsActivity.5.1.1p1)
//
//                                            {
//                                            }
//
//                                            public Intent onIntentRewrite(Intent intent) {
//                                                intent.putExtra("cluster", c(a.b.a.a));
//                                                intent.putExtra("pick_status", f(a.b.a.a));
//                                                intent.putExtra("conversation", d(a.b.a.a));
//                                                return intent;
//                                            }
//                                        });
//                                        b.a.a.finish();
//                                        return;
//                                    }
//                                    g(b.a.a);
//                                }
//                            }
//                        }, 0x1f4);
//                    }
//
//                    public void onException(String code, String reason) {
//                        un.a(code, reason);
//                        e(a.a).clearAnimation();
//                        e(a.a).setEnabled(true);
//                        if (WKManager.isConnected()) {
//                            HashMap dt = new HashMap();
//                            dt.put("senderId", Long.valueOf(c(a.a).sender));
//                            dt.put("clusterId", c(a.a).clusterId);
//                            dt.put("desc", "\uff08\u7f51\u7edc\u6b63\u5e38\uff09 " + code + " " + reason);
//                            bdn alarm = new bdn();
//                            alarm.a = "redpackets";
//                            alarm.b = dt;
//                            alarm.c = 0x44e;
//                            alarm.d = "\u62a2\u7ea2\u5305\u5931\u8d25";
//                            bdk.a().a(alarm);
//                        }
//                    }
//                });
//            }
//        });
//        d.setOnClickListener(new View.OnClickListener(this) {
//
//            6(
//            PickRedPacketsActivity p1
//            )
//
//            {
//            }
//
//            public void onClick(View v) {
//                if (c(a).type == 0x2) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_org_redenvelope_see", new String[0x0]);
//                } else if (d(a).type() == 0x1) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_normal_redenvelope_see", new String[0x0]);
//                } else {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_rand_redenvelope_see", new String[0x0]);
//                }
//                Navigator.from(a).to("https://qr.dingtalk.com/page/red_packets/detail.html", new IntentRewriter(this) {
//
//                    1(PickRedPacketsActivity.6p1)
//
//                    {
//                    }
//
//                    public Intent onIntentRewrite(Intent intent) {
//                        intent.putExtra("cluster", c(a.a));
//                        intent.putExtra("pick_status", f(a.a));
//                        intent.putExtra("conversation", d(a.a));
//                        return intent;
//                    }
//                });
//                a.finish();
//            }
//        });
//        n.setOnClickListener(new View.OnClickListener(this) {
//
//            7(
//            PickRedPacketsActivity p1
//            )
//
//            {
//            }
//
//            public void onClick(View v) {
//                if (c(a).type == 0x2) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_org_redenvelope_see", new String[0x0]);
//                } else if (d(a).type() == 0x1) {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_normal_redenvelope_see", new String[0x0]);
//                } else {
//                    (Statistics) Doraemon.getArtifact("STATISTICS").recordStatistics(0x201, "chat_rand_redenvelope_see", new String[0x0]);
//                }
//                Navigator.from(a).to("https://qr.dingtalk.com/page/red_packets/detail.html", new IntentRewriter(this) {
//
//                    1(PickRedPacketsActivity.7p1)
//
//                    {
//                    }
//
//                    public Intent onIntentRewrite(Intent intent) {
//                        intent.putExtra("cluster", c(a.a));
//                        intent.putExtra("pick_status", f(a.a));
//                        intent.putExtra("conversation", d(a.a));
//                        return intent;
//                    }
//                });
//                a.finish();
//            }
//        });
//    }
//
//    private void a(View view, float start, float end) {
//        float centerX = (float) un.b(mApp, 0.0f) / 2.0f;
//        float centerY = (float) un.b(mApp, 0.0f) / 2.0f;
//        PickRedPacketsActivity.a rotation = new PickRedPacketsActivity.a(this, start, end, centerX, centerY, 0.0f, true);
//        rotation.setDuration(0x3e8);
//        rotation.setRepeatCount(0x7fffffff);
//        rotation.setFillAfter(true);
//        rotation.setInterpolator(new AccelerateInterpolator());
//        rotation.setRepeatMode(0x1);
//        view.startAnimation(rotation);
//    }
//}
