package org.niray.dingtalkluckmoney.code;///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package com.alibaba.android.dingtalk.redpackets.models;
//
//import java.io.Serializable;
//import java.util.List;
//
//public class RedPacketsClusterObject implements Serializable {
//    public String alipayOrderString;
//    public int alipayStatus;
//    public String amount;
//    public String businessId;
//    public String cid;
//    public String clusterId;
//    public String congratulations;
//    public int count;
//    public long createTime;
//    public long modifyTime;
//    public long oid;
//    public long pickDoneTime;
//    public long pickTime;
//    public Long[] receivers;
//    public long sender;
//    public int size;
//    public int status;
//    public int type;
//
//    public static RedPacketsClusterObject fromIDL(qp model) {
//        RedPacketsClusterObject redPacketsClusterDetailObject = new RedPacketsClusterObject();
//        redPacketsClusterDetailObject.createTime = uy.a(a);
//        redPacketsClusterDetailObject.modifyTime = uy.a(a);
//        redPacketsClusterDetailObject.sender = uy.a(c);
//        redPacketsClusterDetailObject.businessId = d;
//        redPacketsClusterDetailObject.clusterId = e;
//        redPacketsClusterDetailObject.amount = f;
//        redPacketsClusterDetailObject.size = uy.a(g);
//        if(h != null) {
//            redPacketsClusterDetailObject.receivers = (Long[])h.toArray(new Long[h.size()]);
//        }
//        redPacketsClusterDetailObject.type = uy.a(i);
//        redPacketsClusterDetailObject.cid = j;
//        redPacketsClusterDetailObject.count = uy.a(k);
//        redPacketsClusterDetailObject.status = uy.a(l);
//        redPacketsClusterDetailObject.oid = uy.a(m);
//        redPacketsClusterDetailObject.congratulations = n;
//        redPacketsClusterDetailObject.pickTime = uy.a(o);
//        redPacketsClusterDetailObject.pickDoneTime = uy.a(p);
//        redPacketsClusterDetailObject.alipayStatus = uy.a(q);
//        redPacketsClusterDetailObject.alipayOrderString = r;
//        return redPacketsClusterDetailObject;
//    }
//}
