package org.niray.dingtalkluckmoney.code;///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package com.alibaba.android.dingtalk.redpackets.models;
//
//import java.io.Serializable;
//
//public class RedPacketsClusterPickingStatus implements Serializable {
//    public RedPacketsClusterDetailObject detail;
//    public int pickStatus;
//    public RedPacketsClusterObject redEnvelopCluster;
//
//    public static RedPacketsClusterPickingStatus fromIDL(qq model) {
//        RedPacketsClusterPickingStatus redPacketsClusterPickingStatus = new RedPacketsClusterPickingStatus();
//        redPacketsClusterPickingStatus.pickStatus = uy.a(a);
//        if(c != null) {
//            redPacketsClusterPickingStatus.detail = RedPacketsClusterDetailObject.fromIDL(c);
//        }
//        redPacketsClusterPickingStatus.redEnvelopCluster = RedPacketsClusterObject.fromIDL(b);
//        return redPacketsClusterPickingStatus;
//    }
//}
