package org.niray.dingtalkluckmoney.code;///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package com.alibaba.android.dingtalk.redpackets;
//
//import com.aliaba.android.dingtalk.redpackets.base.RedPacketInterface;
//import android.text.TextUtils;
//import com.alibaba.android.dingtalkbase.BaseApplication;
//import android.content.Context;
//import android.app.Activity;
//import com.laiwang.framework.navigator.Navigator;
//import com.alibaba.wukong.im.Conversation;
//import com.laiwang.framework.navigator.IntentRewriter;
//import com.alibaba.android.dingtalkbase.widgets.dialog.DDProgressDialog;
//import com.aliaba.android.dingtalk.redpackets.base.models.RedPacketsMessageBodyDo;
//import android.app.Application;
//
//public class RedPacketsInterfaceImpl extends RedPacketInterface {
//    private String a;
//
//    public void a(Activity activity, Conversation conversation, long senderId, String clusterId, int type) {
//        Navigator.from(activity).to("https://qr.dingtalk.com/page/red_packets/detail.html", new IntentRewriter(this, clusterId, senderId, conversation, type) {
//
//            1(RedPacketsInterfaceImpl p1, String p2, long p3, Conversation p4, int p5) {
//            }
//
//            public Intent onIntentRewrite(Intent intent) {
//                intent.putExtra("cluster_id", a);
//                intent.putExtra("sender_id", b);
//                intent.putExtra("conversation", c);
//                intent.putExtra("type", d);
//                return intent;
//            }
//        });
//    }
//
//    public void a(Activity activity) {
//        Navigator.from(activity).to("https://qr.dingtalk.com/page/red_packets/balance.html");
//    }
//
//    public void a(Activity activity, Conversation conversation) {
//        Navigator.from(activity).to("https://qr.dingtalk.com/page/red_packets/send.html", new IntentRewriter(this, conversation) {
//
//            2(RedPacketsInterfaceImpl p1, Conversation p2) {
//            }
//
//            public Intent onIntentRewrite(Intent intent) {
//                intent.putExtra("conversation", a);
//                return intent;
//            }
//        });
//    }
//
//    public void a(Activity activity, Conversation conversation, long senderId, String clusterId) {
//        // :( Parsing error. Please contact me.
//    }
//
//    public void a(Activity activity, Conversation conversation, RedPacketsMessageBodyDo messageBodyDo) {
//        if(messageBodyDo != null) {
//            Navigator.from(activity).to("https://qr.dingtalk.com/page/red_packets/pick.html", new IntentRewriter(this, conversation, messageBodyDo) {
//
//                4(RedPacketsInterfaceImpl p1, Conversation p2, RedPacketsMessageBodyDo p3) {
//                }
//
//                public Intent onIntentRewrite(Intent intent) {
//                    intent.putExtra("conversation", a);
//                    RedPacketsClusterPickingStatus redEnvelopClusterPickingStatusModel = new RedPacketsClusterPickingStatus();
//                    redEnvelopClusterPickingStatusModel.pickStatus = 0x0;
//                    RedPacketsClusterObject clusterObject = new RedPacketsClusterObject();
//                    clusterObject.receivers = b.receivers;
//                    clusterObject.size = b.size;
//                    clusterObject.sender = b.sid;
//                    clusterObject.clusterId = b.clusterid;
//                    clusterObject.congratulations = b.congrats;
//                    clusterObject.amount = b.amount;
//                    redEnvelopClusterPickingStatusModel.redEnvelopCluster = clusterObject;
//                    intent.putExtra("pick_status", redEnvelopClusterPickingStatusModel);
//                    return intent;
//                }
//            });
//        }
//    }
//
//    public void a(String url) {
//        a = url;
//    }
//
//    public String a(String text, int type) {
//        String result = text;
//        if(type == 0x2) {
//            if(TextUtils.isEmpty(result)) {
//                return result;
//            }
//        }
//        if(TextUtils.isEmpty(result)) {
//            return result;
//        }
//        return result;
//    }
//
//    public void a(long uid) {
//        vl.e(tf.a().b(), uid + "binded_alipay");
//    }
//
//    public void init(Application application) {
//    }
//}
