///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package com.alibaba.android.dingtalkim.imtools;
//
//import android.content.Context;
//import android.text.TextUtils;
//
//import com.alibaba.android.dingtalk.userbase.ContactInterface;
//import com.alibaba.android.dingtalk.userbase.model.UserProfileObject;
//import com.alibaba.wukong.Callback;
//import com.alibaba.wukong.im.Conversation;
//import com.alibaba.wukong.im.ConversationService;
//import com.alibaba.wukong.im.IMEngine;
//import com.alibaba.wukong.im.Message;
//import com.alibaba.wukong.im.MessageBuilder;
//
//import org.json.JSONArray;
//import org.json.JSONException;
//import org.json.JSONObject;
//
//import java.lang.reflect.Member;
//import java.util.ArrayList;
//import java.util.Iterator;
//import java.util.List;
//
//public class ConversationTools {
//    private = 0x4;
//    private f = 0x3c;
//
//    private ConversationTools() {
//    }
//    private static ConversationTools g = 0x0;
//
//    public static ConversationTools a() {
//        if(g == null) {
//            g = new ConversationTools();
//        }
//        return g;
//    }
//
//    public Message a(String newTitle) {
//        ArrayList<String> params = new ArrayList<String>();
//        params.add(rb.a().d());
//        params.add(newTitle);
//        Message message = (MessageBuilder)IMEngine.getIMService(MessageBuilder.class).buildTextMessage(0x0, ConversationTools.BuildPurpose.titleChange.getTemplateCode(), params);
//        return message;
//    }
//
//    public String a(List<UserProfileObject> p1, boolean includeSelf) {
//        // :( Parsing error. Please contact me.
//    }
//
//    public List<UserProfileObject> b(String uidString) {
//        if((TextUtils.isEmpty(uidString)) || (!uidString.startsWith("uids:")) && (!uidString.startsWith("$:"))) {
//            return null;
//        }
//        ArrayList<UserProfileObject> profileList = new ArrayList<UserProfileObject>();
//        if(uidString.startsWith("uids:")) {
//            int index = uidString.indexOf(":");
//            uidString = uidString.substring((index + 0x1));
//            String[] uids = uidString.split(";");
//            for(String uid : uids) {
//                UserProfileObject profileObject = new UserProfileObject();
//                profileObject.uid = bgj.g(uid);
//                profileList.add(profileObject);
//            }
//            if(uidString.startsWith("$:")) {
//                index = uidString.indexOf(":");
//                uidString = uidString.substring((index + 0x1));
//                try {
//                    JSONArray jsonArray = new JSONArray(uidString);
//                    for(int i = 0x0; i < jsonArray.length(); i = i + 0x1) {
//                        JSONObject jsonObject = jsonArray.getJSONObject(i);
//                        UserProfileObject userProfileObject = new UserProfileObject();
//                        if(jsonObject.has("uId")) {
//                            userProfileObject.uid = bgj.g(jsonObject.getString("uId"));
//                        }
//                        if(jsonObject.has("nick")) {
//                            userProfileObject.nick = jsonObject.getString("nick");
//                        }
//                        if(jsonObject.has("mediaId")) {
//                            userProfileObject.avatarMediaId = jsonObject.getString("mediaId");
//                        }
//                        profileList.add(userProfileObject);
//                    }
//                } catch(JSONException e) {
//                    e.printStackTrace();
//                }
//            }
//        }
//        return profileList;
//    }
//
//    public String b(List<UserProfileObject> objects, boolean includeSelf) {
//        // :( Parsing error. Please contact me.
//    }
//    Context a = tf.a().b().getApplicationContext();
//    final String b = "%s";
//    final String c = "uids:";
//    final String d = "$:";
//
//    public void a(Conversation conversationObject, List<Long> uids, boolean needNotify) {
//        if(conversationObject == null) {
//            return;
//        }
//        if((uids != null) && (uids.size() != 0)) {
//            List<UserProfileObject> iconList = b(conversationObject.icon());
//            if(iconList == null) {
//                ArrayList iconList = new ArrayList();
//            }
//            if((conversationObject.tag() != 0x2) || (iconList.size() < 0x4)) {
//                for(Long uid : uids) {
//                    UserProfileObject userProfileObject = ContactInterface.a().d(uid.longValue());
//                    if((userProfileObject != null) && (iconList.size() <= 0x4)) {
//                        iconList.add(userProfileObject);
//                    }
//                }
//                String newIconString = b(iconList, false);
//                if((!TextUtils.isEmpty(newIconString)) && (needNotify)) {
//                    conversationObject.updateIcon(newIconString, 0x0, 0x0);
//                }
//            }
//        }
//    }
//
//    public void a(Conversation conversationObject, List<UserProfileObject> curUserList, List<Long> uids, boolean needNotify) {
//        if(conversationObject == null) {
//            return;
//        }
//        if((uids != null) && (uids.size() != 0)) {
//            ArrayList<UserProfileObject> iconList = new ArrayList<UserProfileObject>();
//            iconList.addAll(b(conversationObject.icon()));
//            Iterator<UserProfileObject> iterator = iconList.iterator();
//            while(iterator.hasNext()) {
//                UserProfileObject userProfileObject = (UserProfileObject)iterator.next();
//                if(uids.contains(Long.valueOf(userProfileObject.uid))) {
//                    iterator.remove();
//                }
//            }
//            if((iconList.size() < 0x4) && (curUserList != null) && (curUserList.size() > 0)) {
//                ArrayList<Long> uid = new ArrayList<Long>();
//                for(UserProfileObject object : iconList) {
//                    uid.add(Long.valueOf(object.uid));
//                }
//                if(curUserList.iterator().hasNext()) {
//                    UserProfileObject obj = (UserProfileObject)curUserList.iterator().next();
//                    if((!uid.contains(Long.valueOf(obj.uid))) && (!uids.contains(Long.valueOf(obj.uid)))) {
//                        iconList.add(obj);
//                    }
//                    if(iconList.size() > 0x4) {
//                    }
//                }
//            }
//            if(needNotify) {
//                String newIconString = b(iconList, false);
//                conversationObject.updateIcon(newIconString, 0x0, 0x0);
//            }
//        }
//        // Parsing error may occure here :(
//    }
//
//    public void b(Conversation conversationObject, List<Long> uids, boolean needNotify) {
//        if(conversationObject == null) {
//            return;
//        }
//        if((uids != null) && (uids.size() != 0)) {
//            ArrayList<UserProfileObject> iconList = new ArrayList<UserProfileObject>();
//            List<UserProfileObject> tempList = b(conversationObject.icon());
//            if((tempList != null) && (tempList.size() > 0)) {
//                iconList.addAll(tempList);
//            }
//            Iterator<UserProfileObject> iterator = iconList.iterator();
//            while(iterator.hasNext()) {
//                UserProfileObject userProfileObject = (UserProfileObject)iterator.next();
//                if(uids.contains(Long.valueOf(userProfileObject.uid))) {
//                    iterator.remove();
//                }
//            }
//            if(conversationObject.type() == 0x2) {
//                if(iconList.size() < 0x4) {
//                    (ConversationService)IMEngine.getIMService(ConversationService.class).listMembers(new Callback(this, iconList, needNotify, conversationObject) {
//
//                        1(ConversationTools p1, List p2, boolean p3, Conversation p4) {
//                        }
//
//                        public void a(List<Member> members) {
//                            if(members != null) {
//                                ArrayList<Long> uids = new ArrayList<Long>();
//                                long masterOpenId = 0x0;
//                                for(Member member : members) {
//                                    if(member.roleType() == Member.RoleType.MASTER) {
//                                        masterOpenId = member.user().openId();
//                                    }
//                                    uids.add(Long.valueOf(member.user().openId()));
//                                }
//                                if(masterOpenId [cmp] 0x0 != 0) {
//                                    uids.add(0x0, Long.valueOf(masterOpenId));
//                                }
//                                ArrayList<Long> uid = new ArrayList<Long>();
//                                UserProfileObject object = (UserProfileObject)a.iterator().next()) {
//                                    uid.add(Long.valueOf(object.uid));
//                                }
//                                for(int i = 0x0; i < uids.size(); i = i + 0x1) {
//                                    UserProfileObject obj = ContactInterface.a().d((Long)uids.get(i).longValue());
//                                    if((obj != null) && (!uid.contains(Long.valueOf(obj.uid))) && (a.size() <= 0x4)) {
//                                        a.add(obj);
//                                    }
//                                }
//                                if(b) {
//                                    String newIconString = d.b(a, false);
//                                    c.updateIcon(newIconString, 0x0, 0x0);
//                                }
//                            }
//                        }
//
//                        public void onException(String s, String s2) {
//                            if(b) {
//                                String newIconString = d.b(a, false);
//                                c.updateIcon(newIconString, 0x0, 0x0);
//                            }
//                        }
//
//                        public void a(List<Member> p1, int i) {
//                            // :( Parsing error. Please contact me.
//                        }
//                    }, conversationObject.conversationId(), 0x0, 0x4);
//                    return;
//                }
//                if(needNotify) {
//                    String newIconString = b(iconList, false);
//                    conversationObject.updateIcon(newIconString, 0x0, 0x0);
//                }
//            }
//        }
//        // Parsing error may occure here :(
//    }
//
//    public String a(List<UserProfileObject> p1) {
//        // :( Parsing error. Please contact me.
//    }
//
//    public Message a(List<UserProfileObject> p1, ConversationTools.BuildPurpose buildPurpose) {
//        // :( Parsing error. Please contact me.
//    }
//}
