///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package ;
//
//import com.alibaba.Disappear;
//import com.alibaba.wukong.im.Message;
//import android.view.View;
//import com.alibaba.android.dingtalkbase.widgets.AvatarImageView;
//import android.widget.TextView;
//import android.widget.ImageView;
//import android.view.ViewGroup;
//import android.content.Context;
//import android.view.LayoutInflater;
//import android.view.ViewStub;
//import android.app.Activity;
//import android.text.format.DateUtils;
//
//public abstract class xb {
//    protected AvatarImageView b;
//    protected TextView c;
//    protected TextView d;
//    protected View e;
//    protected View f;
//    protected View g;
//    protected TextView h;
//    protected ImageView i;
//    protected ImageView j;
//    protected TextView k;
//    protected ViewGroup l;
//    protected View m;
//    protected xb.b n;
//    protected Message o;
//
//    public abstract void a(int p1);
//
//
//    public abstract void a(long p1);
//
//
//    public abstract void a(Activity p1, long p2, Message p3, int p4);
//
//
//    protected abstract int b();
//
//
//    protected abstract void b(View p1);
//
//
//    protected abstract int c();
//
//    protected sta = new xb.1();
//    p = 0x0;
//    private View q = 0x0;
//    pr = 0x0;
//    private int s = -0x1;
//
//    public xb() {
//    }
//
//    public void a(View parent) {
//        m = parent;
//    }
//
//    public final View a(Context context) {
//        LayoutInflater inflater = (LayoutInflater)context.getSystemService("layout_inflater");
//        View rootView = inflater.inflate(b(), 0x0);
//        ViewStub viewStub = (ViewStub)rootView.findViewById(xa.f.chatting_content_view_stub);
//        if((viewStub != null) && (c() != 0)) {
//            viewStub.setLayoutResource(c());
//            e = viewStub.inflate();
//        }
//        b = (AvatarImageView)rootView.findViewById(xa.f.chattting_avatar);
//        c = (TextView)rootView.findViewById(xa.f.chatting_title);
//        d = (TextView)rootView.findViewById(xa.f.special_tips);
//        int gmtResourceId = d();
//        if(gmtResourceId != -0x1) {
//            p = (TextView)rootView.findViewById(gmtResourceId);
//            q = rootView.findViewById(xa.f.tv_overlay);
//        }
//        f = rootView.findViewById(xa.f.rl_tips);
//        if(f != null) {
//            j = (ImageView)f.findViewById(xa.f.tips_setting);
//            g = f.findViewById(xa.f.msg_tips);
//            h = (TextView)f.findViewById(xa.f.msg_tips_text);
//            i = (ImageView)f.findViewById(xa.f.msg_tips_icon);
//        }
//        r = rootView.findViewById(xa.f.tv_overlay_new_message_start);
//        k = (TextView)rootView.findViewById(xa.f.chatting_item_hidden_time);
//        l = (ViewGroup)rootView.findViewById(xa.f.chatting_content_view_container);
//        b(rootView);
//        return rootView;
//    }
//
//    public void a() {
//        TextView gmtCreated = e();
//        if(gmtCreated != null) {
//            gmtCreated.setVisibility(0x4);
//        }
//    }
//
//    public void b(long orgId) {
//    }
//
//    public void a(Message message) {
//        o = message;
//    }
//
//    protected int d() {
//        return xa.f.chatting_time_tv;
//    }
//
//    public TextView e() {
//        return p;
//    }
//
//    public final void a(int position, boolean isShowCreatedTime, long createTime) {
//        TextView gmtCreated = e();
//        if(gmtCreated == null) {
//            return;
//        }
//        if(isShowCreatedTime) {
//            gmtCreated.setVisibility(0x0);
//            gmtCreated.setText(uz.a(createTime, true));
//            if(q != null) {
//                q.setVisibility(0x0);
//            }
//        } else {
//            gmtCreated.setVisibility(0x8);
//            if(q != null) {
//                q.setVisibility(0x8);
//            }
//        }
//        if(q != null) {
//            q.setTag("chatting_time_tv_parent");
//        }
//    }
//
//    public void c(long time) {
//        if(k != null) {
//            k.setText(DateUtils.formatDateTime(k.getContext(), time, 0x81));
//        }
//    }
//
//    public void a(float offset) {
//        if((k != null) && (l != null) && (e != null)) {
//            k.setTranslationX(offset);
//            float chatOffset = 0x0;
//            if((l.getWidth() > 0) && (e.getWidth() > 0) && (k.getWidth() > 0)) {
//                int[] chatLocation = new int[0x2];
//                e.getLocationInWindow(chatLocation);
//                float timeLeft = (float)(l.getWidth() - k.getWidth()) + offset;
//                float chatRight = (float)(chatLocation[0x0] + e.getWidth()) - e.getTranslationX();
//                if(timeLeft < chatRight) {
//                    chatOffset = timeLeft - chatRight;
//                }
//            }
//            int childrenLength = l.getChildCount();
//            for(int i = 0x0; i < childrenLength; i = i + 0x1) {
//                View v = l.getChildAt(i);
//                if(v != k) {
//                    v.setTranslationX(chatOffset);
//                }
//            }
//        }
//    }
//
//    public final void a(boolean isShow) {
//        if(r != null) {
//            if(isShow) {
//                r.setVisibility(0x0);
//                return;
//            }
//            r.setVisibility(0x8);
//        }
//    }
//
//    public void a(xb.b listener) {
//        n = listener;
//    }
//
//    public int f() {
//        return s;
//    }
//
//    public void b(int viewTag) {
//        s = viewTag;
//    }
//}
