///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package ;
//
//import android.view.View;
//import com.alibaba.wukong.im.Message;
//import com.alibaba.android.dingtalkim.base.model.MsgDisplayType;
//import android.app.Activity;
//import java.util.List;
//import com.alibaba.android.dingtalkbase.BaseApplication;
//import android.widget.ListView;
//import com.alibaba.android.dingtalkim.base.model.DingtalkMessage;
//import android.view.ViewGroup;
//import android.content.Context;
//
//public class xh extends wb {
//    private View.OnClickListener d;
//    private xb.b es;
//    private long f;
//    private int g;
//    private long h;
//    private long i;
//    private Message j;
//
//    public xh(Activity context, List<Message> list, int conversationType, long conversationTag, xb.b onItemListener) {
//        super(context, list);
//        g = conversationType;
//        h = conversationTag;
//        f = tf.a().b().getCurrentUid();
//        e = onItemListener;
//    }
//
//    public void a(long tag, boolean needUpdate) {
//        if(h [cmp] tag != 0) {
//            h = tag;
//            if(needUpdate != null) {
//                notifyDataSetChanged();
//            }
//        }
//    }
//
//    public void a(long orgId) {
//        i = orgId;
//    }
//
//    public void a(ListView listView) {
//        c = listView;
//    }
//
//    public void a(List<Message> p1) {
//        // :( Parsing error. Please contact me.
//    }
//
//    public void a(Message message) {
//        j = message;
//    }
//
//    public boolean a(int position) {
//        if(position >= getCount()) {
//            return false;
//        }
//        return true;
//    }
//
//    public View getView(int position, View convertView, ViewGroup parent) {
//        int ordinal = getItemViewType(position);
//        if(convertView != null) {
//            xb viewHolder = (xb)convertView.getTag();
//            if(viewHolder.f() != ordinal) {
//                convertView = 0x0;
//            }
//        }
//        if(convertView == null) {
//            viewHolder = aah.a(MsgDisplayType.getTypeByOrdinal(ordinal));
//            viewHolder.a(e);
//            convertView = viewHolder.a(b);
//            convertView.setTag(viewHolder);
//        } else {
//            viewHolder = (xb)convertView.getTag();
//            viewHolder.a();
//        }
//        viewHolder.a(parent);
//        viewHolder.b(ordinal);
//        if(convertView instanceof ViewGroup) {
//            if(d != null) {
//                convertView.setOnClickListener(d);
//            }
//        }
//        Message message = b(position);
//        if(message == null) {
//            return convertView;
//        }
//        long currentL = b(message);
//        boolean isShowCreateTime = 0x1;
//        if(d()) {
//            if((position - 0x1) >= 0) {
//                Message tmp = (Message)a.get((position - 0x1));
//                if(tmp != null) {
//                    Long preT = Long.valueOf((currentL - b(tmp)));
//                    isShowCreateTime = Math.abs(preT.longValue()) >= 0xdbba0 ? true : false;
//                }
//            }
//        }
//        if(message.equals(j)) {
//            viewHolder.a(true);
//        } else {
//            viewHolder.a(false);
//        }
//        viewHolder.a(h);
//        viewHolder.b(i);
//        viewHolder.a(message);
//        viewHolder.a(position, isShowCreateTime, currentL);
//        viewHolder.c(currentL);
//        viewHolder.a(g);
//        viewHolder.a(a(), f, message, this);
//        aat.a().a(f, message);
//        aas.a().a(message, h);
//        if(e != null) {
//            e.a(position, message, convertView);
//        }
//        return convertView;
//    }
//
//    protected long b(Message message) {
//        return message.createdAt();
//    }
//
//    protected boolean d() {
//        return true;
//    }
//
//    public int getItemViewType(int position) {
//        DingtalkMessage message = (DingtalkMessage)b(position);
//        return message.msgDisplayType.ordinal();
//    }
//
//    public Message b(int position) {
//        int count = getCount();
//        if((position < 0) || (position > count)) {
//            return null;
//        }
//        return (Message)a.get(position);
//    }
//    private static final int k = MsgDisplayType.values().length;
//
//    public int getViewTypeCount() {
//        return k;
//    }
//
//    public void notifyDataSetChanged() {
//        super.notifyDataSetChanged();
//    }
//
//    public void a(View.OnClickListener click) {
//        d = click;
//    }
//}
