///**
// * Generated by smali2java 1.0.0.558
// * Copyright (C) 2013 Hensence.com
// */
//
//package ;
//
//import android.widget.BaseAdapter;
//import android.content.Context;
//import java.util.List;
//import com.alibaba.android.dingtalkim.base.model.DingtalkConversation;
//import java.util.ArrayList;
//import android.widget.ListView;
//import com.alibaba.android.dingtalk.userbase.model.UserIconObject;
//import com.alibaba.android.dingtalkbase.widgets.AvatarImageView;
//import com.alibaba.wukong.im.Conversation;
//import android.view.View;
//import java.util.Map;
//import java.util.HashMap;
//import android.text.TextUtils;
//import com.alibaba.android.dingtalkim.base.IMInterface;
//import android.view.ViewGroup;
//import android.view.LayoutInflater;
//import android.widget.TextView;
//import android.content.res.Resources;
//import android.graphics.drawable.Drawable;
//
//public class xs extends BaseAdapter {
//    private Context b;
//    private List<DingtalkConversation> c;
//    priva = xs.class.getSimpleName();
//
//    public xs(Context context, List<DingtalkConversation> conversationObjects) {
//        b = context;
//        c = conversationObjects;
//    }
//
//    public int getCount() {
//        return c == null ? 0x0 : c.size();
//    }
//
//    public Object getItem(int position) {
//        return c.get(position);
//    }
//
//    public long getItemId(int position) {
//        return (long)position;
//    }
//
//    public View getView(int position, View convertView, ViewGroup parent) {
//        if(convertView == null) {
//            xs.a holder = new xs.a(this);
//            convertView = LayoutInflater.from(b).inflate(xa.g.forward_session_item, 0x0);
//            holder.a = (AvatarImageView)convertView.findViewById(xa.f.session_icon);
//            holder.b = convertView.findViewById(xa.f.three_avatar);
//            holder.d = new AvatarImageView[0x3];
//            holder.d[0x0] = (AvatarImageView)holder.b.findViewById(xa.f.session_user_icon0);
//            holder.d[0x1] = (AvatarImageView)holder.b.findViewById(xa.f.session_user_icon1);
//            holder.d[0x2] = (AvatarImageView)holder.b.findViewById(xa.f.session_user_icon2);
//            holder.c = convertView.findViewById(xa.f.four_avatar);
//            holder.e = new AvatarImageView[0x4];
//            holder.e[0x0] = (AvatarImageView)holder.c.findViewById(xa.f.session_user_icon0);
//            holder.e[0x1] = (AvatarImageView)holder.c.findViewById(xa.f.session_user_icon1);
//            holder.e[0x2] = (AvatarImageView)holder.c.findViewById(xa.f.session_user_icon2);
//            holder.e[0x3] = (AvatarImageView)holder.c.findViewById(xa.f.session_user_icon3);
//            holder.f = (TextView)convertView.findViewById(xa.f.session_title);
//            holder.g = convertView.findViewById(xa.f.session_top);
//            convertView.setTag(holder);
//        } else {
//            holder = (xs.a)convertView.getTag();
//        }
//        DingtalkConversation object = (DingtalkConversation)c.get(position);
//        a(holder, object, parent);
//        if((object != null) && (object.mConversation != null) && (object.mConversation.type() == 0x1)) {
//            if((object.mConversation != null) && (object.mConversation.tag() == 0x4)) {
//                Drawable pic = b.getResources().getDrawable(xa.e.ic_conversation_safe_lock);
//                pic.setBounds(0x0, 0x0, 0x18, 0x1e);
//                holder.f.setCompoundDrawables(0x0, 0x0, pic, 0x0);
//                holder.f.setCompoundDrawablePadding(un.b(b, 3.0f));
//            } else {
//                holder.f.setCompoundDrawables(0x0, 0x0, 0x0, 0x0);
//            } else if((object != null) && (object.mConversation != null) && (object.mConversation.type() == 0x2)) {
//                if((object.mConversation != null) && (object.mConversation.tag() == 0x2)) {
//                    if(un.c()) {
//                        if(object.mConversation.extension("deptId") != null) {
//                            pic = b.getResources().getDrawable(xa.e.enterprise_dept_cornor_icon_for_session_fragment);
//                        } else {
//                            pic = b.getResources().getDrawable(xa.e.enterprise_cornor_icon_for_session_fragment);
//                        } else if(object.mConversation.extension("deptId") != null) {
//                            pic = b.getResources().getDrawable(xa.e.enterprise_dept_cornor_icon_for_session_fragment_en);
//                        } else {
//                            pic = b.getResources().getDrawable(xa.e.enterprise_cornor_icon_for_session_fragment_en);
//                        }
//                    }
//                    pic.setBounds(0x0, 0x0, 0x20, 0x20);
//                    holder.f.setCompoundDrawables(0x0, 0x0, pic, 0x0);
//                    holder.f.setCompoundDrawablePadding(un.b(b, 3.0f));
//                } else {
//                    holder.f.setCompoundDrawables(0x0, 0x0, 0x0, 0x0);
//                }
//            }
//        }
//        if((object != null) && (object.mConversation != null)) {
//            title = object.mConversation.title();
//        }
//        if((object != null) && (object.mConversation != null) && (object.mConversation.type() == 0x1)) {
//            if((object.mediaIdList != null) && (object.mediaIdList.size() > 0)) {
//                String title = (UserIconObject)object.mediaIdList.get(0x0).nick;
//            } else {
//                title = object.mConversation.title();
//            }
//        }
//        if((object != null) && (object.mConversation != null) && (object.mConversation.type() == 0x2) && (object.mConversation.totalMembers() > 0)) {
//            holder.f.setText(title + "(" + b.getString(xa.h.member_count, new Object[] {Integer.valueOf(object.mConversation.totalMembers())}) + ")");
//        } else {
//            holder.f.setText(title);
//        }
//        if(object != null) {
//            holder.f.setTag(object.mConversation);
//        }
//        if(object.mConversation.getTop() > 0x0) {
//            holder.g.setVisibility(0x0);
//            return convertView;
//        }
//        holder.g.setVisibility(0x8);
//        return convertView;
//    }
//
//    public void a(xs.a holder, DingtalkConversation data, ListView parent) {
//        if(data.mConversation.type() == 0x1) {
//            holder.a.setVisibility(0x0);
//            holder.b.setVisibility(0x8);
//            holder.c.setVisibility(0x8);
//            if((data.mediaIdList == null) || (data.mediaIdList.size() == 0)) {
//                holder.a.setVisibility(0x0);
//                long receiverUid = aan.a(data.mConversation.conversationId());
//                holder.a.b(String.valueOf(receiverUid), 0x0, parent);
//                return;
//            }
//            UserIconObject object = (UserIconObject)data.mediaIdList.get(0x0);
//            if(object == null) {
//                holder.a.setVisibility(0x8);
//                return;
//            }
//            holder.a.a();
//            if(data.mConversation.tag() == 0x4) {
//                holder.a.setBurnChat(true);
//            } else {
//                holder.a.setBurnChat(false);
//            }
//            holder.a.b(object.nick, object.mediaId, parent);
//            return;
//        }
//        if(data.mConversation.type() == 0x2) {
//            String singleIcon = aan.a((HashMap)data.mConversation.extension(), (int)data.mConversation.tag());
//            if((TextUtils.isEmpty(singleIcon)) && (data != null) && (data.mConversation != null)) {
//                singleIcon = IMInterface.a().a(data.mExtension);
//            }
//            if(!TextUtils.isEmpty(singleIcon)) {
//                holder.a.setVisibility(0x0);
//                holder.b.setVisibility(0x8);
//                holder.c.setVisibility(0x8);
//                holder.a.setBurnChat(false);
//                holder.a.a(0x0, singleIcon, parent);
//                return;
//            }
//            if((data.mediaIdList == null) || (data.mediaIdList.size() == 0)) {
//                holder.b.setVisibility(0x8);
//                holder.c.setVisibility(0x8);
//                holder.a.setVisibility(0x8);
//                return;
//            }
//            holder.a.setVisibility(0x8);
//            if(data.mediaIdList.size() == 0x1) {
//                holder.a.setVisibility(0x0);
//                holder.b.setVisibility(0x8);
//                holder.c.setVisibility(0x8);
//                holder.a.setBurnChat(false);
//                holder.a.setDefaultRes(xa.e.default_conversation_icon);
//                holder.a.b((UserIconObject)data.mediaIdList.get(0x0).nick, (UserIconObject)data.mediaIdList.get(0x0).mediaId, parent);
//                return;
//            }
//            holder.a.a();
//            if(data.mediaIdList.size() < 0x4) {
//                holder.b.setVisibility(0x0);
//                holder.c.setVisibility(0x8);
//                a(holder, data.mediaIdList, 0x3, parent);
//                return;
//            }
//            holder.b.setVisibility(0x8);
//            holder.c.setVisibility(0x0);
//            a(holder, data.mediaIdList, 0x4, parent);
//        }
//    }
//
//    private void a(xs.a holder, ArrayList<UserIconObject> p2, int max, ListView parent) {
//        int size = p2.size();
//        for(int i = 0x0; i < max; i = i + 0x1) {
//            if(i < size) {
//                UserIconObject object = (UserIconObject)p2.get(i);
//                if(max == 0x4) {
//                    avatarList.e[i].b(object.nick, object.mediaId, parent);
//                    continue;
//                }
//                avatarList.d[i].b(object.nick, object.mediaId, parent);
//                continue;
//            }
//            avatarList.d[i].setImageResource(xa.e.avatar_nobody);
//        }
//    }
//}
